import logger from "../config/logger.js";
import AuditLog from "../models/AuditLog.js";

export const AUDIT_ACTIONS = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  PASSWORD_RESET: "PASSWORD_RESET",
  DOCTOR_APPROVAL: "DOCTOR_APPROVAL",
  DOCTOR_REJECTION: "DOCTOR_REJECTION",
  ACCOUNT_SUSPENSION: "ACCOUNT_SUSPENSION",
  PATIENT_PROFILE_VIEW: "PATIENT_PROFILE_VIEW",
  PATIENT_PROFILE_UPDATE: "PATIENT_PROFILE_UPDATE",
  PATIENT_PROFILE_PICTURE_UPLOAD: "PATIENT_PROFILE_PICTURE_UPLOAD",
  PATIENT_DASHBOARD_VIEW: "PATIENT_DASHBOARD_VIEW",
  PATIENT_NOTIFICATIONS_VIEW: "PATIENT_NOTIFICATIONS_VIEW",
  PATIENT_APPOINTMENTS_VIEW: "PATIENT_APPOINTMENTS_VIEW",
  DOCTOR_DISCOVERY_VIEW: "DOCTOR_DISCOVERY_VIEW",
  DOCTOR_PROFILE_VIEW: "DOCTOR_PROFILE_VIEW",
  APPOINTMENT_COMPLETE: "APPOINTMENT_COMPLETE",
  PRESCRIPTION_CREATE: "PRESCRIPTION_CREATE",
  DOCTOR_APPOINTMENTS_VIEW: "DOCTOR_APPOINTMENTS_VIEW",
  DOCTOR_PATIENT_VIEW: "DOCTOR_PATIENT_VIEW",
  DOCTOR_DASHBOARD_VIEW: "DOCTOR_DASHBOARD_VIEW",
  APPOINTMENT_CREATE: "APPOINTMENT_CREATE",
  APPOINTMENT_CANCEL: "APPOINTMENT_CANCEL",
  APPOINTMENT_RESCHEDULE: "APPOINTMENT_RESCHEDULE",
  APPOINTMENT_CONFIRM: "APPOINTMENT_CONFIRM",
  APPOINTMENT_STATUS_UPDATE: "APPOINTMENT_STATUS_UPDATE",
  APPOINTMENT_VIEW: "APPOINTMENT_VIEW",
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUND_APPROVED: "REFUND_APPROVED",
  REFUND_REJECTED: "REFUND_REJECTED",
  REFUND_COMPLETED: "REFUND_COMPLETED"
};

export const createAuditLog = async ({
  actorId = null,
  actorRole = "system",
  action,
  resourceType,
  resourceId = null
}) => {
  try {
    await AuditLog.create({
      actorId,
      actorRole,
      action,
      resourceType,
      resourceId,
      timestamp: new Date()
    });
  } catch (error) {
    logger.warn("Failed to create audit log", {
      action,
      resourceType,
      error: error.message
    });
  }
};
